### ISSUE TITLE
Madparts KiCad exporter exports module names containing spaces

### ISSUE THREAD

**Issue by seppestas** [andete/madparts#106]
Following the [KiCad file formats specification](http://bazaar.launchpad.net/~stambaughw/kicad/doc-read-only/download/head:/1115%4016bec504-3128-0410-b3e8-8e38c2123bca:trunk%252Fkicad-doc%252Fdoc%252Fhelp%252Ffile_formats%252Ffile_formats.pdf/file_formats.pdf) chapter 4.4 - Identifiers and Strings:
A string may not contain an actual newline or carriage return, but it may use an escape sequence to encode a
newline, such as \n.
If a string has any of the following conditions, then it must be quoted with a leading and trailing double quote
character, otherwise it is acceptable to not quote the string:
1. has one or more of the following 4 separator bytes: ASCII space, tab, '(', or ')'.
2. has one or more of the following bytes: '%', '{', or '}'.
3. has a length of zero bytes, and you need a place holder for the field, then use "".
4. includes a byte of '-', and this byte is not in the first position of the string.

A string, including a module name, should be quoted when it contains an ASCII space character. However, [Madpart's KiCad exporter](https://github.com/andete/madparts/blob/master/export/kicad.py) exports the module name with an escaped space character instead quoting the name.

I did not test if this also occurs on different fields.

**Comment by andete** [comment]
Thanks for the detailed description. This seems indeed to be a problem.
A fix will be made soonish.
