### ISSUE TITLE
Making all or even some pad names blank, causes Kicad to ignore pretty mod file

### ISSUE THREAD

**Issue by spanner888** [andete/madparts#85]
example code:

  pad3 = new Smd 
  pad3.name = ""
  pad3.dx = tp_t_width
  pad3.dy = tp_t_length
  pad3.x = -tp_t_width -  1.25 +  pad3.dx/2
  pad3.y = 1.4 +  pad3.dy/2
  pad3.ro = 0

Output text is  
  pad  smd rect (....
instead of  
  pad "" smd rect (....

**Comment by spanner888** [comment]
thanks for the super quick fix, it works well and especially thanks for a really great tool

**Comment by andete** [comment]
You're welcome!
